services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE broadcaster_test;' -U postgres
language : node_js
node_js : 
    - "stable"
script: 
    - "npm run test"
after_success: 
    - "npm run coveralls"
